<?php
declare(strict_types=1);

return [
    'featured' => [
        'slug' => 'otshudi-disashi-kalonda-jean-baptiste',
        'name' => 'OTSHUDI DISASHI-KALONDA Jean-Baptiste',
        'display_name' => 'OTSHUDI DISASHI-KALONDA Jean-Baptiste',
        'initials' => 'JBO',
        'role' => 'Co-Founder and COO',
        'link'=>'#',
        'location' => 'LabCongo, Kinshasa, DRC',
        'image' => '',
        'avatar_class' => 'bg-primary',
        'socials' => [
            'facebook' => '#',
            'twitter' => '#',
            'linkedin' => '#',
            'youtube' => '#',
        ],
        'bio' => [
            'Jean-Baptiste Otshudi Disashi-Kalonda is an experienced lawyer and senior executive with more than 20 years of experience in law, public governance, and the mining sector in the Democratic Republic of Congo.',
            'He contributes to LabCongo through strategic leadership, legal insight, and a strong commitment to responsible mining-sector services.',
            'His profile reflects a focus on discipline, transparency, traceability, and professional collaboration in support of reliable laboratory operations.',
        ],
    ],
    'members' => [
        [
            'slug' => 'longendja-isamboyo-henri-christin',
            'name' => 'LONGENDJA ISAMBOYO Henri Christin',
            'display_name' => 'LONGENDJA H.C',
            'initials' => 'L.H-C',
            'role' => 'Team Member',
            'link' => '#',
            'location' => 'LabCongo, Kinshasa, DRC',
            'image' => '',
            'avatar_class' => 'bg-secondary',
            'socials' => ['facebook' => '#', 'twitter' => '#', 'linkedin' => '#', 'youtube' => '#'],
            'bio' => [
                "LONGENDJA ISAMBOYO Henri Christin contributes to LabCongo's team and supports the company's mining laboratory services.",
                'This profile is part of the official team list prepared for the LabCongo website.',
                'Additional responsibilities and detailed biography information can be added as the profile is completed.',
            ],
        ],
        [
            'slug' => 'musoga-bakaato-kethia',
            'name' => 'MUSOGA BAKAATO Kethia',
            'display_name' => 'MUSOGA Kethia',
            'initials' => 'M.K',
            'role' => 'Team Member',
            'link' => '#',
            'location' => 'LabCongo, Kinshasa, DRC',
            'image' => '',
            'avatar_class' => 'bg-dark',
            'socials' => ['facebook' => '#', 'twitter' => '#', 'linkedin' => '#', 'youtube' => '#'],
            'bio' => [
                "MUSOGA BAKAATO Kethia contributes to LabCongo's team and supports the company's mining laboratory services.",
                'This profile is part of the official team list prepared for the LabCongo website.',
                'Additional responsibilities and detailed biography information can be added as the profile is completed.',
            ],
        ],
        [
            'slug' => 'itamba-yonkos-benjamin',
            'name' => 'ITAMBA Y’ONKOS Benjamin',
            'display_name' => 'ITAMBA Benjamin',
            'initials' => 'I.B',
            'role' => 'Team Member',
            'link' => '#',
            'location' => 'LabCongo, Kinshasa, DRC',
            'image' => '',
            'avatar_class' => 'bg-primary',
            'socials' => ['facebook' => '#', 'twitter' => '#', 'linkedin' => '#', 'youtube' => '#'],
            'bio' => [
                "ITAMBA Y’ONKOS Benjamin contributes to LabCongo's team and supports the company's mining laboratory services.",
                'This profile is part of the official team list prepared for the LabCongo website.',
                'Additional responsibilities and detailed biography information can be added as the profile is completed.',
            ],
        ],
        [
            'slug' => 'lombi-evy',
            'name' => 'LOMBI Evy',
            'display_name' => 'LOMBI Evy',
            'initials' => 'L.E',
            'role' => 'Voir Plus',
            'link' => '#',
            'location' => 'LabCongo, Kinshasa, DRC',
            'image' => '',
            'avatar_class' => 'bg-secondary',
            'socials' => ['facebook' => '#', 'twitter' => '#', 'linkedin' => '#', 'youtube' => '#'],
            'bio' => [
                "LOMBI Evy contributes to LabCongo's team and supports the company's mining laboratory services.",
                'This profile is part of the official team list prepared for the LabCongo website.',
                'Additional responsibilities and detailed biography information can be added as the profile is completed.',
            ],
        ],
    ],
];
