<?php
declare(strict_types=1);

return [
    'featured' => [
        'slug' => 'otshudi-dishashi-jean-baptiste',
        'name' => 'OTSHUDI DISHASHI Jean Baptiste',
        'display_name' => 'OTSHUDI Jean Baptiste',
        'initials' => 'OD',
        'role' => 'Co-Founder and COO',
        'location' => 'LabCongo, Kinshasa, DRC',
        'image' => 'img/team-1.jpg',
        'avatar_class' => 'bg-primary',
        'socials' => [
            'facebook' => '#',
            'twitter' => '#',
            'linkedin' => '#',
            'youtube' => '#',
        ],
        'bio' => [
            'Jean Baptiste Otshudi Dishashi is an experienced lawyer and senior executive with more than 20 years of experience in law, public governance, and the mining sector in the Democratic Republic of Congo.',
            'He contributes to LabCongo through strategic leadership, legal insight, and a strong commitment to responsible mining-sector services.',
            'His profile reflects a focus on discipline, transparency, traceability, and professional collaboration in support of reliable laboratory operations.',
        ],
    ],
    'members' => [
        [
            'slug' => 'longendja-isamboyo-henri-christian',
            'name' => 'LONGENDJA ISAMBOYO Henri Christian',
            'display_name' => 'LONGENDJA Henri Christian',
            'initials' => 'LI',
            'role' => 'Team Member',
            'location' => 'LabCongo, Kinshasa, DRC',
            'image' => '',
            'avatar_class' => 'bg-secondary',
            'socials' => ['facebook' => '#', 'twitter' => '#', 'linkedin' => '#', 'youtube' => '#'],
            'bio' => [
                "LONGENDJA ISAMBOYO Henri Christian contributes to LabCongo's team and supports the company's mining laboratory services.",
                'This profile is part of the official team list prepared for the LabCongo website.',
                'Additional responsibilities and detailed biography information can be added as the profile is completed.',
            ],
        ],
        [
            'slug' => 'musoga-bakaato-kethia',
            'name' => 'MUSOGA BAKAATO Kethia',
            'display_name' => 'MUSOGA Kethia',
            'initials' => 'MB',
            'role' => 'Team Member',
            'location' => 'LabCongo, Kinshasa, DRC',
            'image' => '',
            'avatar_class' => 'bg-dark',
            'socials' => ['facebook' => '#', 'twitter' => '#', 'linkedin' => '#', 'youtube' => '#'],
            'bio' => [
                "MUSOGA BAKAATO Kethia contributes to LabCongo's team and supports the company's mining laboratory services.",
                'This profile is part of the official team list prepared for the LabCongo website.',
                'Additional responsibilities and detailed biography information can be added as the profile is completed.',
            ],
        ],
        [
            'slug' => 'itamba-yonkos-benjamin',
            'name' => "ITAMBA Y'ONKOS Benjamin",
            'display_name' => "ITAMBA  Benjamin",
            'initials' => 'IY',
            'role' => 'Team Member',
            'location' => 'LabCongo, Kinshasa, DRC',
            'image' => '',
            'avatar_class' => 'bg-primary',
            'socials' => ['facebook' => '#', 'twitter' => '#', 'linkedin' => '#', 'youtube' => '#'],
            'bio' => [
                "ITAMBA Y'ONKOS Benjamin contributes to LabCongo's team and supports the company's mining laboratory services.",
                'This profile is part of the official team list prepared for the LabCongo website.',
                'Additional responsibilities and detailed biography information can be added as the profile is completed.',
            ],
        ],
        [
            'slug' => 'lombi-evy',
            'name' => 'LOMBI Evy',
            'display_name' => 'LOMBI Evy',
            'initials' => 'LE',
            'role' => 'Team Member',
            'location' => 'LabCongo, Kinshasa, DRC',
            'image' => '',
            'avatar_class' => 'bg-secondary',
            'socials' => ['facebook' => '#', 'twitter' => '#', 'linkedin' => '#', 'youtube' => '#'],
            'bio' => [
                "LOMBI Evy contributes to LabCongo's team and supports the company's mining laboratory services.",
                'This profile is part of the official team list prepared for the LabCongo website.',
                'Additional responsibilities and detailed biography information can be added as the profile is completed.',
            ],
        ],
        [
            'slug' => 'michel-delarose-masumuna',
            'name' => 'MICHEL DELAROSE MASUMUNA',
            'display_name' => 'MASUMUNA Michel Delarose',
            'initials' => 'MD',
            'role' => 'Team Member',
            'location' => 'LabCongo, Kinshasa, DRC',
            'image' => '',
            'avatar_class' => 'bg-dark',
            'socials' => ['facebook' => '#', 'twitter' => '#', 'linkedin' => '#', 'youtube' => '#'],
            'bio' => [
                "MICHEL DELAROSE MASUMUNA contributes to LabCongo's team and supports the company's mining laboratory services.",
                'This profile is part of the official team list prepared for the LabCongo website.',
                'Additional responsibilities and detailed biography information can be added as the profile is completed.',
            ],
        ],
        [
            'slug' => 'musau-ruth',
            'name' => 'MUSAU Ruth',
            'display_name' => 'MUSAU Ruth',
            'initials' => 'MR',
            'role' => 'Team Member',
            'location' => 'LabCongo, Kinshasa, DRC',
            'image' => '',
            'avatar_class' => 'bg-primary',
            'socials' => ['facebook' => '#', 'twitter' => '#', 'linkedin' => '#', 'youtube' => '#'],
            'bio' => [
                "MUSAU Ruth contributes to LabCongo's team and supports the company's mining laboratory services.",
                'This profile is part of the official team list prepared for the LabCongo website.',
                'Additional responsibilities and detailed biography information can be added as the profile is completed.',
            ],
        ],
        [
            'slug' => 'wasongo-kanda-jorgen',
            'name' => 'WASONGO KANDA Jorgen',
            'display_name' => 'WASONGO Jorgen',
            'initials' => 'WK',
            'role' => 'Team Member',
            'location' => 'LabCongo, Kinshasa, DRC',
            'image' => '',
            'avatar_class' => 'bg-secondary',
            'socials' => ['facebook' => '#', 'twitter' => '#', 'linkedin' => '#', 'youtube' => '#'],
            'bio' => [
                "WASONGO KANDA Jorgen contributes to LabCongo's team and supports the company's mining laboratory services.",
                'This profile is part of the official team list prepared for the LabCongo website.',
                'Additional responsibilities and detailed biography information can be added as the profile is completed.',
            ],
        ],
    ],
];
