<?php
declare(strict_types=1);

return [
    'featured' => [
        'slug' => 'jean-baptiste-otshudi-disashi-kalonda',
        'name' => 'Dir. Jean-Baptiste Otshudi Disashi Kalonda',
        'display_name' => 'Dir. Jean-Baptiste Otshudi',
        'initials' => 'JO',
        'role' => 'Co-Founder and COO',
        'location' => 'LabCongo, Kinshasa, DRC',
        'image' => 'img/team-1.jpg',
        'avatar_class' => 'bg-primary',
        'socials' => [
            'facebook' => '#',
            'twitter' => '#',
            'linkedin' => '#',
            'youtube' => '#',
        ],
        'bio' => [
            'An experienced lawyer and senior executive, Jean-Baptiste Otshudi Disashi Kalonda has more than 20 years of experience in law, public governance, and the mining sector in the Democratic Republic of Congo. Currently Legal Director and Director for the Fight Against Mining Fraud at CEEC, he is recognized for his deep command of mining law, litigation, and mechanisms for regulating and certifying natural resources.',
            'With a strong background in economic and social law from the University of Kinshasa, he has held several strategic positions within public institutions, including the National Assembly and various ministries. His career reflects recognized expertise in legal advisory work, regulatory drafting, and public affairs management.',
            'A rigorous and committed professional with a strong team spirit, he has contributed to major initiatives related to transparency, mineral traceability, and the fight against mining fraud at both national and international levels.',
        ],
    ],
    'members' => [
        [
            'slug' => 'longendja-isamboyo-henri-christin',
            'name' => 'LONGENDJA ISAMBOYO Henri Christin',
            'display_name' => 'LONGENDJA Henri Christin',
            'initials' => 'LI',
            'role' => 'Team Member',
            'location' => 'LabCongo, Kinshasa, DRC',
            'image' => '',
            'avatar_class' => 'bg-secondary',
            'socials' => ['facebook' => '#', 'twitter' => '#', 'linkedin' => '#', 'youtube' => '#'],
            'bio' => [
                "Henri Christin Longendja Isamboyo contributes to LabCongo's mission by supporting the coordination of laboratory activities and mining-analysis workflows.",
                'His work helps strengthen sample follow-up, operational discipline, and collaboration between the technical team and project stakeholders.',
                'He is part of the team committed to reliable results, clear communication, and responsible service delivery for mining-sector clients.',
            ],
        ],
        [
            'slug' => 'otshudi-akangambo-laelle',
            'name' => 'OTSHUDI AKANGAMBO Laelle',
            'display_name' => 'OTSHUDI Laelle',
            'initials' => 'OA',
            'role' => 'Team Member',
            'location' => 'LabCongo, Kinshasa, DRC',
            'image' => '',
            'avatar_class' => 'bg-dark',
            'socials' => ['facebook' => '#', 'twitter' => '#', 'linkedin' => '#', 'youtube' => '#'],
            'bio' => [
                'Laelle Otshudi Akangambo supports LabCongo through team coordination, administrative follow-up, and attention to the quality of client-facing processes.',
                'Her contribution helps the laboratory maintain organized communication, reliable documentation, and a professional service experience.',
                'She is involved in the collective effort to make LabCongo a trusted partner for mining laboratory services.',
            ],
        ],
        [
            'slug' => 'toussaint-molenge-mangenza',
            'name' => 'Toussaint MOLENGE MANGENZA',
            'display_name' => 'Toussaint MANGENZA',
            'initials' => 'TM',
            'role' => 'Team Member',
            'location' => 'LabCongo, Kinshasa, DRC',
            'image' => '',
            'avatar_class' => 'bg-primary',
            'socials' => ['facebook' => '#', 'twitter' => '#', 'linkedin' => '#', 'youtube' => '#'],
            'bio' => [
                "Toussaint Molenge Mangenza contributes to the organization and monitoring of LabCongo's laboratory-support activities.",
                'He supports the team in keeping project information clear, sample-related processes traceable, and operational priorities aligned with client needs.',
                "His role reinforces LabCongo's focus on discipline, reliability, and teamwork in the mining laboratory environment.",
            ],
        ],
        [
            'slug' => 'mukendi-kabuya-gaby',
            'name' => 'MUKENDI KABUYA Gaby',
            'display_name' => 'MUKENDI Gaby',
            'initials' => 'MK',
            'role' => 'Team Member',
            'location' => 'LabCongo, Kinshasa, DRC',
            'image' => '',
            'avatar_class' => 'bg-secondary',
            'socials' => ['facebook' => '#', 'twitter' => '#', 'linkedin' => '#', 'youtube' => '#'],
            'bio' => [
                "Gaby Mukendi Kabuya supports LabCongo's operational and project follow-up activities, helping the team maintain consistency in service delivery.",
                'His contribution is connected to coordination, documentation, and the practical organization required for reliable laboratory work.',
                'He is part of the team working to provide accurate, traceable, and client-oriented mining analysis services.',
            ],
        ],
        [
            'slug' => 'itamba-yonkos-benjamin',
            'name' => "ITAMBA Y'ONKOS Benjamin",
            'display_name' => 'ITAMBA Benjamin',
            'initials' => 'IY',
            'role' => 'Team Member',
            'location' => 'LabCongo, Kinshasa, DRC',
            'image' => '',
            'avatar_class' => 'bg-dark',
            'socials' => ['facebook' => '#', 'twitter' => '#', 'linkedin' => '#', 'youtube' => '#'],
            'bio' => [
                "Benjamin Itamba Y'Onkos contributes to LabCongo's technical and operational support activities in the mining laboratory context.",
                'He helps maintain practical follow-up around samples, project needs, and internal coordination so that the team can respond efficiently to client requests.',
                "His work supports LabCongo's broader commitment to reliable analysis, disciplined processes, and continuous improvement.",
            ],
        ],
        [
            'slug' => 'mungoba-balilia-roger',
            'name' => 'MUNGOBA BALILIA Roger',
            'display_name' => 'MUNGOBA Roger',
            'initials' => 'MB',
            'role' => 'Team Member',
            'location' => 'LabCongo, Kinshasa, DRC',
            'image' => '',
            'avatar_class' => 'bg-primary',
            'socials' => ['facebook' => '#', 'twitter' => '#', 'linkedin' => '#', 'youtube' => '#'],
            'bio' => [
                'Roger Mungoba Balilia supports LabCongo through operational follow-up and coordination related to mining laboratory services.',
                'His contribution helps maintain traceability, communication, and practical organization across the activities that support analytical work.',
                'He is part of the team dedicated to dependable service, responsible mining support, and professional collaboration.',
            ],
        ],
        [
            'slug' => 'otshudi-germaine',
            'name' => 'OTSHUDI Germaine',
            'display_name' => 'OTSHUDI Germaine',
            'initials' => 'OG',
            'role' => 'Team Member',
            'location' => 'LabCongo, Kinshasa, DRC',
            'image' => '',
            'avatar_class' => 'bg-secondary',
            'socials' => ['facebook' => '#', 'twitter' => '#', 'linkedin' => '#', 'youtube' => '#'],
            'bio' => [
                "Germaine Otshudi contributes to LabCongo's team by supporting communication, organization, and client-oriented follow-up.",
                'Her role helps reinforce the quality of the service experience and the internal discipline needed for reliable laboratory operations.',
                "She is part of LabCongo's commitment to professionalism, trust, and clear support for mining-sector partners.",
            ],
        ],
        [
            'slug' => 'manu',
            'name' => 'MANU',
            'display_name' => 'MANU',
            'initials' => 'M',
            'role' => 'Team Member',
            'location' => 'LabCongo, Kinshasa, DRC',
            'image' => '',
            'avatar_class' => 'bg-dark',
            'socials' => ['facebook' => '#', 'twitter' => '#', 'linkedin' => '#', 'youtube' => '#'],
            'bio' => [
                "Manu supports LabCongo's daily team activities and contributes to the practical organization of laboratory-service workflows.",
                'This contribution helps the team maintain responsiveness, coordination, and consistency in the way client requests are followed.',
                "Manu is part of the collective effort behind LabCongo's reliable and professional mining laboratory services.",
            ],
        ],
    ],
];
